services: 
  
  db:
      image: postgres:latest
      restart: always
      environment: 
        - POSTGRES_USER=course
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=movies
      ports:
        - '5432:5432'